#!/usr/bin/env bash

if [[ $SCRIPT_DEBUG ]]; then
	set -x
fi

deepin_compatibility_mode_path="$(dirname "${0}")"

main() {
	options=$(getopt -n dcm -l "deb-id:" -o "hv" -- "$@")
	eval set -- "$options"

	deb_id=""
	while true; do
		case "$1" in
		-h)
			echo "TODO"
			exit
			;;
		-v)
			echo "TODO"
			exit
			;;
		--deb-id)
			deb_id="$2"
			shift 2
			;;
		--container)
			container="$2"
			shift 2
			;;
		--)
			shift
			break
			;;
		esac
	done

	if [ -z "$container" ]; then
		container=$(. "$deepin_compatibility_mode_path/deepin-compatibility-mode-container" "$deb_id")
		container=$(echo "$container" | jq -r ".name")
	fi

	debs=()
	while IFS= read -r -d $'\0'; do
		debs+=("\"${REPLY/#//run/host}\"")
	done < <(find /opt/apps/"$deb_id"/files -name '*.deb' -print0)

	notify-send \
		'deepin V20 compatibility mode' \
		'Loading application.' \
		--icon=dialog-information

	distrobox enter -n "$container" -- bash -c \
		"sudo apt install -y dde-qt5integration dde-qt5xcb-plugin"

	distrobox enter -n "$container" -- bash -c \
		"sudo cp ${debs[*]} /var/cache/apt/archives" || exit 255
	distrobox enter -n "$container" -- bash -c \
		"sudo apt install -y ${debs[*]}" || exit 255
	exec distrobox enter -n "$container" -- bash -c \
		"sudo deepin-app-store-tool" || exit 255
}

main "$@"
