#!/usr/bin/env bash

if [[ $SCRIPT_DEBUG ]]; then
	set -x
fi

deb_id=$1
shift

# TODO(black_desk): search db or somehow get container configuration

echo '{
        "name": "DeepinV20.8CompatibilityMode",
        "image": "docker.io/linuxdeepin/apricot"
}'
